name: TradePlus
version: ${project.version}
author: [Trophonix, JacobC]
main: com.trophonix.tradeplus.TradePlus
softdepend: [Vault,EnjinMinecraftPlugin,GriefPrevention,PlayerPoints,TokenManager,BeastTokens,TokenEnchant,WorldGuard,VotingPlugin]
api-version: "1.21"
commands:
  trade:
    description: Trade command
  tradeplus:
    description: TradePlus admin command
    permission: tradeplus.admin
permissions:
  tradeplus.admin:
    description: TradePlus admin permission
    default: op
    children:
      tradeplus.trade: true
  tradeplus.admin.silent:
    description: Silence admin trade notifications
    default: false